Update all pre-commit hook version and fix the resulting errors (#24)
* Update pre-commit repo revs.

* Remove `mdformat-openmmlab` and `mdformat_frontmatter` as they are no longer maintained and not support mdformat rev 1.0.0.

* `fix-encoding-pragma` has been removed -- use `pyupgrade` from https://github.com/asottile/pyupgrade

* Fix detected flake8 F824.

* Auto modified by pre-commit hooks after pre-commit autoupdate.

* Fix mypy error: No overload variant of "join" matches argument types "SimplePath", "str"  [call-overload]

* Fix mypy error: No overload variant of "__add__" of "tuple" matches argument type "InstanceData"  [operator]

* Fix mypy error: "<typing special form>" has no attribute "__args__"  [attr-defined]

* Fix mypy error: Argument 2 to "copy" has incompatible type "str | Path"; expected "str"  [arg-type]

* Fix mmengine/runner/runner.py:1428: error: "Any" not callable  [misc].
Fix mmengine/runner/runner.py:1439: error: Argument "num_workers" to "worker_init_fn" has incompatible type "Any | None"; expected "int"  [arg-type].

* Fix mypy mmengine/runner/_flexible_runner.py:866: error: "Any" not callable  [misc].
Fix mypy mmengine/runner/_flexible_runner.py:877: error: Argument "num_workers" to "worker_init_fn" has incompatible type "Any | None"; expected "int"  [arg-type].

* Release `flake8` `max-line-length` to 90 to avoid aggressive code modification.

* Accomplish TODO: if filepath or filepaths are Path, should return Path.
There're test unit logical modification in this commit.

* Fix test script: To disable validation during training, It's better to set `val_begin` to infinite instead of `val_interval`. Because the logic of `EpochBasedTrainLoop` will call validate at the end of the last epoch. And this will not happen when `self._epoch < self.val_begin`.

* `fileio.join_path` will return `pathlib.Path` or `str` according to input type. `test_io` unit should be modified.

* Revert pre-commit modifications related to `mdformat`, and it auto modifies several markdown.

* Fix the incorrect return type annotation and fix the resulting mypy error.

* Improve readability